set nocp
filetype plugin on
:set pastetoggle=<f5>
" tab navigation
map <A-left>     :tabp<CR>
map <A-right>    :tabn<CR>
map <A-S-left>   :tabmove -1<CR>
map <A-S-right>  :tabmove +1<CR>
map <F2>         :Explore<CR>
nnoremap <C-S-t> :tabnew<CR>
inoremap <C-S-t> <Esc>:tabnew<CR>

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
  set tabstop=2 shiftwidth=2 expandtab
  filetype plugin indent on
endif
